// Reference to base url 
@base_url = https://localhost:3443

// Home page 
GET {{base_url}}

###
// Get all accounts
GET {{base_url}}/accounts

###
// Add User 
POST {{base_url}}/accounts
Content-Type: application/json

{
  
    "client_id": "test",
    "balance": "150",
    "alias": "test"

}

### 
// Get specific account from id 
GET {{base_url}}/accounts/5fa55f093a8e520ee0205991

### 
// Alter the balance on an account 
PUT {{base_url}}/accounts/5fa55f093a8e520ee0205991
Content-Type: application/json

{
    "balance": "123456789"
}

###
// Delete a user 
DELETE {{base_url}}/accounts/5fa5725f52991d12f427977f












###
//Get all clients 
GET {{base_url}}/client

###
//Get balance for an accounts (in this case Christopher)
GET {{base_url}}/accounts/Christopher 


###

//Add a user
POST {{base_url}}/accounts/add 
Content-Type: application/json

{
    "firstName": "Rasmus",
    "lastName": "Rasmussen",
    "balance": "150",
    "branch": "CBS Banking branch 1"

}