// Reference to base url 
@base_url = https://localhost:8080

// Home page 
GET {{base_url}}

###
// Get all accounts
GET {{base_url}}/accounts

###
// Add Account 
POST {{base_url}}/accounts
Content-Type: application/json

{
  
    "client_id": "Mads",
    "balance": "100",
    "alias": "Mads"

}

### 
// Get specific account from id 
GET {{base_url}}/accounts/5fb7c8d3516e832f98595507

### 
// Alter an account 
PUT {{base_url}}/accounts/5fb7c8d3516e832f98595507
Content-Type: application/json

{
    "balance": 123456789,
    "alias":"Altered Alias"
}

###
// Delete a Account 
DELETE {{base_url}}/accounts/5fb295a1244cce3944792d86


###
// Balance for a specific account using id
GET {{base_url}}/accounts/5fb29590244cce3944792d84/balance


### 
//Transfering funds from one account to another 
PUT {{base_url}}/accounts/transfer 
Content-Type: application/json

{
    "fromAccount": "5fb29598244cce3944792d85",
    "toAccount": "5fb29590244cce3944792d84",
    "amount": 50
}



###
//Get all clients 
GET {{base_url}}/client


###
//Add a Client
POST {{base_url}}/client
Content-Type: application/json

{
    "firstName": "Mads",
    "lastName": "Rasmussen",
    "street_address": "Egilsgade 55, 3th",
    "city": "kbh"
    

}

### 
// Get information about client using specific ID 
GET {{base_url}}/client/5fb5733024dfe730841ed90b


### 
//Updating information about Client 
PUT {{base_url}}/client/5fb5733024dfe730841ed90b
Content-Type: application/json

{
    "firstName": "Mads",
    "lastName": "Eriksen",
    "street_address": "Egilsgade 55, 3th",
    "city": "kbh"
}

###
// Delete a Client 
DELETE {{base_url}}/client/5fb2a7717c42cd2108581d9d