// Reference to base url 
@base_url = https://localhost:8080

// Home page 
GET {{base_url}}

###
// Get all accounts
GET {{base_url}}/accounts

###
// Add Account 
POST {{base_url}}/accounts
Content-Type: application/json

{
  
    "client_id": "42",
    "balance": "12345",
    "alias": "Chris"

}

### 
// Get specific account from id 
GET {{base_url}}/accounts/5fce40b0f7b07b36dc50489c

### 
// Alter an account 
PUT {{base_url}}/accounts/5fce40b0f7b07b36dc50489c
Content-Type: application/json

{
    "balance": 123456789,
    "alias":"Altered Alias"
}

###
// Delete a Account 
DELETE {{base_url}}/accounts/5fce40b0f7b07b36dc50489c


###
// Balance for a specific account using id
GET {{base_url}}/accounts/5fce40b0f7b07b36dc50489c/balance


### 
//Transfering funds from one account to another 
PUT {{base_url}}/accounts/transfer 
Content-Type: application/json

{
    "fromAccount": "5fce4092f7b07b36dc50489b",
    "toAccount": "5fce40b0f7b07b36dc50489c",
    "amount": 50
}



###
//Get all clients 
GET {{base_url}}/clients


###
//Add a Client
POST {{base_url}}/clients
Content-Type: application/json

{
    "firstname": "Per",
    "lastname": "Rasmussen",
    "streetAddress": "Strøget 55, 3th",
    "city": "kbh"
    

}

### 
// Get information about client using specific ID 
GET {{base_url}}/clients/5fce410ef7b07b36dc50489d


### 
//Updating information about Client 
PUT {{base_url}}/clients/5fce410ef7b07b36dc50489d
Content-Type: application/json

{
    "firstname": "Torben"
}

###
// Delete a Client 
DELETE {{base_url}}/clients/5fce410ef7b07b36dc50489d